### ISSUE TITLE
Fetch current TV shows and news 📺🗞️

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/feini#12]
Get current popular TV shows from [TMDB](https://www.themoviedb.org/) and current news from [DW](https://www.dw.com/en/top-stories/s-9097).

## Draft

```python
@dataclass
class Content:
    """Media content."""

    """Title of the content."""
    title: str

    # Future reference
    """URL of the content or information about it."""
    url: str
    """Short summary."""
    summary: str | None = None

    @staticmethod
    def parse(data: str) -> Content:
        """Parse the string representation *data* into media content."""

class TMDB:
    """The Movie Database source."""

    """Time to live for cached content."""
    CACHE_TTL = timedelta(days=1)

    """API key to fetch the current popular TV shows."""
    key: str | None = None

    """Current TV shows, ordered by popularity, highest first."""
    shows: list[Content] = [Content('Buffy the Vampire Slayer')]

    async def close(self) -> None:
        """Close the source."""

class DW:
    """Deutsche Welle source."""

    """Time to live for cached content."""
    CACHE_TTL = timedelta(days=1)

    """Current news articles, ordered by time, latest first."""
    news: list[Content] = [Content('Digital pet Tamagotchi turns 25')]

    async def close(self) -> None:
        """Close the source."""

class Bot:
    """The Movie Database source."""
    tmdb: TMDB

    """Deutsche Welle source."""
    dw: DW
```

## Tasks

* [x] Implement draft
* [x] `TMDB`: Log fetching
* [x] `TMDB.close()`: Cancel task
* [x] `DW`: Handle feedparser errors
* [x] `TMDB` / `DW`: Rename `_expires` to `_cache_expires`
* [x] `TelevisionTest.test_use()` / `NewspaperTest.test_use()`: Check `show` / `article` against `TMDB` / `DW`
* [x] `fe.ini`: Add `tmdb` section
* [x] Add `TMDBTest` / `DWTest`
