### ISSUE TITLE
View furniture details 📺

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/feini#13]
Let the player view details about a furniture piece, like its state or content.

## Draft

Add `Content.url` and `summary` (see #12).

```
🌺 The houseplant is in full bloom.

📺 Buffy the Vampire Slayer is on. Into every generation a slayer is born: one girl in all the
world, a chosen one. She alone will wield the strength and skill to fight the vampires, demons, and
the forces of darkness; to stop the spread of their evil and the swell of their number. She is the
Slayer. https://www.themoviedb.org/tv/95-buffy-the-vampire-slayer

🗞️ Digital pet Tamagotchi turns 25. Adorable, or annoying? The tiny digital egg beeped in the
pockets of millions of children all over the world. But the hype surrounding the little nuisance
ended as quickly as it began. https://www.dw.com/en/digital-pet-tamagotchi-turns-25/a-61709227

🖼️ The painting is composed of abstract patterns in gentle colors, which still evoke a delicate
impression of reality.
```

## Tasks

* [x] Implement draft
* [x] Use `collapse()` utility
* [x] `Content`: Validate `url`
* [x] `TMDB`: Handle optional overview
* [x] Merge updates into `update_content_url()`
* [x] `view_television()` / `view_newspaper()`: Make summary optional
