### ISSUE TITLE
Add NPCs 👻

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/feini#4]
Let the player talk to NPCs.

## Draft

```python
@dataclass
class Message:
    """Dialogue message."""

    """Message ID."""
    id: str
    """Items the character currently needs, if any."""
    request: list[str]
    """Items the player has just given to the character, if any."""
    taken: list[str]

    @staticmethod
    def parse(data: str) -> Message:
        """Parse the string representation *data* into a message."""

    def encode(self) -> str:
        """Return a string representation of the message."""

class Character:
    """Character."""

    """Character ID."""
    id: str
    """Related :class:`Space` ID."""
    space_id: str
    """Avatar emoji."""
    avatar: str

    async def get_dialogue(self) -> list[Message]:
        """Get the ongoing dialogue, starting from the most recent message."""

    async def talk(self) -> Message:
        """Talk to the character and return their reply.

        If the character has requested some items, give the items to them or repeat the request
        message.
        """

class Space:
    async def get_characters(self) -> list[Character]:
        """Get the present characters."""
```

Talk actions:

```
👻 Where am I?
```

## Tasks

* [x] Implement draft
* [x] `Space.get_characters()`: Wrap in transaction
* [x] `Message`: Validate attributes
* [x] `view_tent()`: Visualize furniture with `str()`
* [x] `talk_to_character()`: Get character by args or return absence message
* [x] `CharacterTest`: Create character with `GhostStory`

**Comment by adilaxmdv** [comment]
good working
