### ISSUE TITLE
Tell ghost story 👻

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/feini#6]
Add a quest which unlocks the sewing needle blueprint.

## Draft

```python
class Story:
    """Short story."""

    """Story ID."""
    id: str
    """Related :class:`Space` ID."""
    space_id: str
    """Current point in the story."""
    state: str
    """Tick the state was updated at."""
    update_tick: int

    async def tell(self) -> None:
        """Continue to the next point in the story if the relevant conditions are met."""
        raise NotImplementedError()

class Space:
    async def get_stories(self) -> set[Story]:
        """Get all active stories."""
```

Ghost 👻, a regretful parent:

* Where am I?
* The last thing I remember is sitting in my chair, making a scarf for my daughter.
* Dear, do you know where I could find 🧶🧶🧶?
* Please, let me return the favor and introduce you to sewing.
* Do you think she will forgive me?

## Tasks

* [x] Implement draft
* [x] `Story`: Rename `state` and `update_tick` to `chapter` and `update_time`
* [x] `Space.get_stories()`: Get type directly from module
* [x] `Space.tell_stories()`
* [x] `Story`: Use `Bot.time`
* [x] `IntroStory`: Add start chapter
* [x] `IntroStory`: Prefix events with `space-explain`
